SELECT name, day FROM CUSTOMERS AS C JOIN RESERVATION AS R ON C.customer_id=R.customer_id
SELECT name, day FROM CUSTOMERS, RESERVATION WHERE CUSTOMERS.customer_id=RESERVATION.customer_id
SELECT name, day FROM CUSTOMERS NATURAL JOIN RESERVATION
SELECT name, day FROM CUSTOMERS CROSS JOIN RESERVATION
SELECT name, day FROM CUSTOMERS, RESERVATION
SELECT name, day FROM CUSTOMERS LEFT JOIN RESERVATION ON CUSTOMERS.customer_id=RESERVATION.customer_id
SELECT name, day FROM CUSTOMERS LEFT JOIN RESERVATION USING (customer_id)
SELECT name, day FROM CUSTOMERS NATURAL LEFT OUTER JOIN RESERVATION
SELECT * FROM CARS
SELECT name, price FROM CARS
SELECT * FROM CARS LIMIT 4
SELECT * FROM CARS LIMIT 2,4
SELECT * FROM CARS LIMIT 4 OFFSET 2
SELECT * FROM CARS ORDER BY price
SELECT name, price FROM CARS ORDER BY price DESC
SELECT * FROM ORDERS
SELECT * FROM ORDERS WHERE id=6
SELECT * FROM ORDERS WHERE customer='Smith'
SELECT * FROM ORDERS WHERE customer LIKE 'B%'
SELECT customer FROM ORDERS WHERE customer LIKE 'B%'
SELECT DISTINCT customer FROM ORDERS WHERE customer LIKE 'B%'
SELECT SUM(order_price) AS total, customer FROM ORDERS GROUP BY customer
SELECT SUM(order_price) AS total, customer FROM ORDERS GROUP BY customer HAVING SUM(order_price) > 1000
INSERT INTO CUSTOMERS (name, day) VALUES ('u12312340', '11')
SELECT name FROM CUSTOMERS WHERE customer_id=0 ORDER BY name
SELECT name FROM CUSTOMERS WHERE customer_id='i00' ORDER BY name
SELECT neme FROM CUSTOMERS WHERE 
