BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS CUSTOMERS (customer_id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO CUSTOMERS(name) VALUES ('Paul Novak');
INSERT INTO CUSTOMERS(name) VALUES ('Tory Neils');
INSERT INTO CUSTOMERS(name) VALUES ('Jack Fonda');
INSERT INTO CUSTOMERS(name) VALUES ('Tom Willis');

CREATE TABLE IF NOT EXISTS RESERVATION (id INTEGER PRIMARY KEY, customer_id INTEGER, day TEXT);
INSERT INTO RESERVATION(customer_id, day) VALUES (1, '2009-22-11');
INSERT INTO RESERVATION(customer_id, day) VALUES (2, '2009-28-11');
INSERT INTO RESERVATION(customer_id, day) VALUES (2, '2009-29-11');
INSERT INTO RESERVATION(customer_id, day) VALUES (1, '2009-29-11');
INSERT INTO RESERVATION(customer_id, day) VALUES (3, '2009-02-12');

CREATE TABLE IF NOT EXISTS AUTHORS (author_id INTEGER PRIMARY KEY, name TEXT);
INSERT INTO AUTHORS VALUES (1, 'Jane Austen');
INSERT INTO AUTHORS VALUES (2, 'Leo Tolstoy');
INSERT INTO AUTHORS VALUES (3, 'Joseph Heller');
INSERT INTO AUTHORS VALUES (4, 'Charles Dickens');

CREATE TABLE IF NOT EXISTS BOOKS (book_id INTEGER PRIMARY KEY, title TEXT, author_id INTEGER, FOREIGN KEY(author_id) REFERENCES AUTHORS(author_id));
INSERT INTO BOOKS VALUES (1, 'Emma', 1);
INSERT INTO BOOKS VALUES (2, 'War and Peace', 2);
INSERT INTO BOOKS VALUES (3, 'Catch XII', 3);
INSERT INTO BOOKS VALUES (4, 'David Copperfield', 4);
INSERT INTO BOOKS VALUES (5, 'Good as Gold', 3);
INSERT INTO BOOKS VALUES (6, 'Anna Karenia', 2);

CREATE TABLE IF NOT EXISTS FRIENDS (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL, sex TEXT CHECK(sex IN ('M','F')));
INSERT INTO FRIENDS VALUES (1, 'Jane', 'F');
INSERT INTO FRIENDS VALUES (2, 'Thomas', 'M');
INSERT INTO FRIENDS VALUES (3, 'Franklin', 'M');
INSERT INTO FRIENDS VALUES (4, 'Elisabeth', 'F');
INSERT INTO FRIENDS VALUES (5, 'Mary', 'F');
INSERT INTO FRIENDS VALUES (6, 'Lucy', 'F');
INSERT INTO FRIENDS VALUES (7, 'Jack', 'M');

CREATE TABLE IF NOT EXISTS ORDERS (id INTEGER PRIMARY KEY, order_price INTEGER CHECK(order_price > 0), customer TEXT);
INSERT INTO ORDERS(order_price, customer) VALUES (1200, 'Williamson');
INSERT INTO ORDERS(order_price, customer) VALUES (200, 'Robertson');
INSERT INTO ORDERS(order_price, customer) VALUES (40, 'Robertson');
INSERT INTO ORDERS(order_price, customer) VALUES (1640, 'Smith');
INSERT INTO ORDERS(order_price, customer) VALUES (100, 'Robertson');
INSERT INTO ORDERS(order_price, customer) VALUES (50, 'Williamson');
INSERT INTO ORDERS(order_price, customer) VALUES (150, 'Smith');
INSERT INTO ORDERS(order_price, customer) VALUES (250, 'Smith');
INSERT INTO ORDERS(order_price, customer) VALUES (840, 'Brown');
INSERT INTO ORDERS(order_price, customer) VALUES (440, 'Black');
INSERT INTO ORDERS(order_price, customer) VALUES (20, 'Brown');

COMMIT;
